
import React, { createContext, useContext, useState, useEffect } from "react";
import { User, AuthState } from "../types";
import { currentUser } from "../data/mockData";

interface AuthContextType extends AuthState {
  login: (email: string, password: string) => Promise<void>;
  logout: () => void;
  register: (name: string, email: string, password: string) => Promise<void>;
}

const initialState: AuthState = {
  isAuthenticated: false,
  user: null,
  isLoading: true,
  error: null,
};

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
};

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [authState, setAuthState] = useState<AuthState>(initialState);

  useEffect(() => {
    // Check if user is already logged in from localStorage
    const storedUser = localStorage.getItem("user");
    if (storedUser) {
      try {
        const user = JSON.parse(storedUser);
        setAuthState({
          isAuthenticated: true,
          user,
          isLoading: false,
          error: null,
        });
      } catch (error) {
        localStorage.removeItem("user");
        setAuthState({
          ...initialState,
          isLoading: false,
        });
      }
    } else {
      setAuthState({
        ...initialState,
        isLoading: false,
      });
    }
  }, []);

  // For a real app, these functions would make API calls
  const login = async (email: string, password: string) => {
    setAuthState({
      ...authState,
      isLoading: true,
      error: null,
    });

    try {
      // This is a mock login, in a real app it would be an API call
      if (email === "john@example.com" && password === "password") {
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 800));
        
        // Store user in localStorage
        localStorage.setItem("user", JSON.stringify(currentUser));
        
        setAuthState({
          isAuthenticated: true,
          user: currentUser,
          isLoading: false,
          error: null,
        });
      } else {
        throw new Error("Invalid email or password");
      }
    } catch (error) {
      setAuthState({
        ...authState,
        isLoading: false,
        error: error instanceof Error ? error.message : "Login failed",
      });
    }
  };

  const logout = () => {
    localStorage.removeItem("user");
    setAuthState({
      isAuthenticated: false,
      user: null,
      isLoading: false,
      error: null,
    });
  };

  const register = async (name: string, email: string, password: string) => {
    setAuthState({
      ...authState,
      isLoading: true,
      error: null,
    });

    try {
      // This is a mock registration, in a real app it would be an API call
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 800));
      
      // In a real app, this would be the newly created user returned from the API
      const newUser: User = {
        id: '6', // This would be generated by the server
        name,
        email,
        avatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        isOnline: true,
      };
      
      // Store user in localStorage
      localStorage.setItem("user", JSON.stringify(newUser));
      
      setAuthState({
        isAuthenticated: true,
        user: newUser,
        isLoading: false,
        error: null,
      });
    } catch (error) {
      setAuthState({
        ...authState,
        isLoading: false,
        error: error instanceof Error ? error.message : "Registration failed",
      });
    }
  };

  return (
    <AuthContext.Provider
      value={{
        ...authState,
        login,
        logout,
        register,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};
